title: Di Sun's Homepage
page-top-title: Di Sun's Homepage
# top-section-bg-text: Computer Science
# home-subtitle: Sen Li&ensp;|&ensp;李森
home-subtitle: 孙迪
# copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
